### PR TITLE
sparkUser added

### LINKED ISSUE #474: Capture 'sparkUser' in the event extras
as per #473

Since it's available in the `SparkContext`, we can easily capture it by default. Many people ask for that.
Perhaps we could simply create a predefined rules for the `userExtraMeta` filter and use it as a default.

### PR DESCRIPTION
**Pull request by vishalag001**
Added sparkUser to extras to plan and event Object

### CODE REVIEW

**Comment by vishalag001** [comment]
@wajda Please review the above PR

**Comment by wajda** [comment]
Thank you for the PR.
My only question would be why do you capture the user in both execution plan and event objects?
I think this information is only relevant for the execution event, because the plan record can be linked to multiple runs (events) potentially triggered by different users.

**Comment by wajda** [comment]
Also, can you please change the commit message, so that it refers the issue number. We have a rule to always refer the issue number in commit messages. Something like `Issue #474 capture sparkUser`

**Comment by vishalag001** [comment]
I'll remove the user info from plan and include the issue number too

**Comment by vishalag001** [comment]
@wajda I have updated the PR

**Review by wajda — APPROVED** [review]
LGTM

**Comment by wajda** [comment]
Merged. Thank you @vishalag001 for contribution.

**Pull request merged**
