### PR TITLE
Feature Request #277 : Bigquery plugin (Plugins API)

### PR DESCRIPTION
**Pull request by wajda**
backport of #294 to _release/0.6_ + addressing PR comments

### CODE REVIEW

**Comment by wajda** [comment]
I've found further issues with the PR:
1. Contradicting dependencies - `spark-bigquery-with-dependencies` contains repackaged classes from its dependencies including `TableId` which is imported by the `BigQueryPlugin`.
2. The _Source URI_ constructed incorrectly. It has to contain _Project_, _Dataset_ and _Table_. Ideally using BigQuery format (`project:dataset.table`)
3. Another Scala reflection error ("_error reading Scala signature_") occurs in the `ReflectioUtils`. It has to be handled.

**Comment by wajda** [comment]
waiting for AbsaOSS/commons#81

**Comment by wajda** [comment]
commons 0.0.30 released, this PR is unblocked

**Review by cerveada — DISMISSED** [review]

**Comment by wajda** [comment]
@mohanajuhi166 Could you please test this PR on your end?
I've partially re-implemented the BigQuery support in this PR, tested it locally with Spark 2.3, 24, 3.0 and 3.1  and it seems to work as I think it should.
The main difference is that it captures _ProjectID_ in addition to _Dataset_ and _Table_ and constructs a consistent URI that resembles the full table ID as Google uses - `<project>:<dataset>.<table>` - for both read and write.

I didn't test it in the Notebook though.

**Comment by wajda** [comment]
The JARs can be found here - https://teamcity.jetbrains.com/buildConfiguration/OpenSourceProjects_AbsaOSS_SplineAgentSpark_PullRequestsSpark31scala212/3614116?buildTab=artifacts#%2Fbundle-3.1;%2Fbundle-3.0;%2Fbundle-2.4

**Comment by wajda** [comment]
Tested on _Databricks_, run into more reflection errors. A part of the fix is implemented in Commons 0.0.31 - AbsaOSS/commons#81.

**Review by cerveada — APPROVED** [review]

**Comment by mohanajuhi166** [comment]
Hello @wajda tested the PR. Read information is working fine .
I had faced some issues with write and currently on it.

**Comment by abhishekshenoy** [comment]
@wajda I had taken the BigQuery Plugin and added it in the 0.6.1 version, was able to capture the read lineage but was unable to capture the write lineage when we use spark-bigquery-connector to write to bq.

**Comment by wajda** [comment]
@abhishekshenoy 0.6.4 captures both _read_ and _write_. It was released today and will be deployed to the Maven Central shortly.

**Comment by abhishekshenoy** [comment]
@wajda I tried it with 0.6.4 , but i am still facing the same issue
Screen Shot 2021-09-17 at 8 19 00 AM

**Comment by wajda** [comment]
I'm not sure I understand the issue. Do you mean that the output being `gs://` instead of `bigquery://`? That's OK, there has to be another write. Since the _bigquery-connector_ writes to a GS bucket first as an intermediate storage Spline captures two execution plans - one to GS and the other one to BQ.

If you only see a single execution plan per write in Spline there might be an error while capturing the second one. Please check Spark logs and open a new issue with the logs attached.
Thank you.

**Comment by abhishekshenoy** [comment]
@wajda Write from GCS to BQ is a BQ load operation and as it is not a spark action , it would not be captured by spline.
https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/0.22.1/connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala#L109

**Comment by wajda** [comment]
It is in fact captured, according to the testing I've done locally as well as on the Databricks notebook.

The following job produces two write events:

1. Write to GCS:
```json
{"write":{"outputSource":"gs://bigquery-tmp1/.spark-bigquery-local-1631879103465-b93546d8-6d30-418c-a804-c0fef874055f","append":false,"id":"0","name":"InsertIntoHadoopFsRelationCommand","childIds":["1"],"params":{"path":"gs://bigquery-tmp1/.spark-bigquery-local-1631879103465-b93546d8-6d30-418c-a804-c0fef874055f"},"extra":{"destinationType":"parquet"}}}
```
2. Write to BQ:
```json
{"write":{"outputSource":"bigquery://spline-325618:test.bigquery_result","append":false,"id":"0","name":"SaveIntoDataSourceCommand","childIds":["1"],"params":{"path":"test.bigquery_result"},"extra":{"destinationType":"bigquery"}}}
```

```scala
val InputBQTable = "bigquery-public-data:baseball.games_post_wide"
val OutputBQTable = s"test.bigquery_result"

val df1 = spark
  .read
  .format("bigquery")
  .load(InputBQTable)

val df2 = df1
  .select('gameId, 'hitterFirstName, 'hitterLastName)
  .distinct
  .limit(10)

df2
  .write
  .format("bigquery")
  .mode("overwrite")
  .save("test.bigquery_result")
```

**Pull request merged**
