### PR TITLE
issue #410 Fix file name collision on case-insensitive filesystems

### LINKED ISSUE #410: Does not compile on windows due to name collision on case-insensitive filesystem
I tried to compile spline-spark-agent on windows, but as it has a case-insensitive filesystem, git threw an error shown below:
```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala'
  'core/src/main/scala/za/co/absa/spline/harvester/idGenerators.scala'
Done
```

This in turn prevented the build-all.sh script from completing successfully due to errors related to the IdGenerators.scala file as shown below:
```
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala:23: object IdGenerator is not a member of package za.co.absa.spline.harvester
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala:40: not found: type UUIDVersion
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/agent/AgentBOM.scala:61: not found: type UUIDVersion
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/agent/SplineAgent.scala:23: object IdGenerator is not a member of package za.co.absa.spline.harvester
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/agent/SplineAgent.scala:55: not found: type UUIDGeneratorFactory
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:19: object IdGenerator is not a member of package za.co.absa.spline.harvester
[ERROR] C:/00/Spline/spline-spark-agent/core/src/main/scala/za/co/absa/spline/harvester/IdGenerators.scala:25: not found: type UUIDGeneratorFactory
```

### PR DESCRIPTION
**Pull request by wajda**
- Rename `IdGenerators` to `IdGeneratorsBundle`
- Extract `IdGeneratorsBundle` related test case from `IdGeneratorSpec` into a new `IdGeneratorsBundleSpec`

### CODE REVIEW

**Comment by cerveada** [comment]
The changes are ok, but should the file `idGenerators.scala` start with lowercase? Seems like keeping everything uppercase would have the effect of avoiding such issues.

**Comment by wajda** [comment]
> ... but should the file `idGenerators.scala` start with lowercase? ... keeping everything uppercase ...

Do you mean the first letter case? This is a Scala naming convention for multi-unit files.

> **All multi-unit files should be given camelCase names with a lower-case first letter.** This is a very important convention. It differentiates multi- from single-unit files, greatly easing the process of finding declarations.
See: https://docs.scala-lang.org/style/files.html#multi-unit-files

**Review by cerveada — APPROVED** [review]

**Comment by abhishekshenoy** [comment]
@wajda  any plans on adding [763e720](https://github.com/AbsaOSS/spline-spark-agent/commit/763e720db0b6d32c10b81c759a699aa72d8f9236) in the next release ?

**Comment by wajda** [comment]
It has been merged to the main branch and will be available in the next release 1.0.0

**Comment by wajda** [comment]
I've backported it into a stable 0.7 series. I'll release a new update (0.7.5) tomorrow.

**Pull request merged**
