### PR TITLE
#669 - Add code coverage support improve

### LINKED ISSUE #669: Improve code-coverage & add GH check action
## Background
Improve or add code coverage support to be able measure code quality.

## Feature
New ability to measure current code coverage as one of QA metrics.
Add GH action to check changed file coverage.

### PR DESCRIPTION
**Pull request by miroslavpojer**
- Used Absa fork of JaCoCo solution - with scala method filtering.
- Added support for code coverage GitHub action check as part of PR.

Closes #669

### CODE REVIEW

**Comment by cerveada** [comment]
Does this coverage take into account the integration-tests or just the standard unit tests?

**Comment by miroslavpojer** [comment]
> Does this coverage take into account the integration-tests or just the standard unit tests?

Total project coverage is measured and counted only for core module in project. For coverage measuring are used tests which are inside of this module.

**Comment by cerveada** [comment]
This project is somewhat atypical in that it relies heavily on integration tests. A huge portion of logic here is matching and extracting objects coming from Spark, and we need to test that it works for every version of Spark and Scala supported. 

So unit test are useless for a big part of the code, we used them to test the internal logic of course, but that is the smaller part of the codebase.

I think we need to either include the integration test in the metric (not sure if it's possible) or drop the requirement for minimal coverage percentage.

**Comment by miroslavpojer** [comment]
> This project is somewhat atypical in that it relies heavily on integration tests. A huge portion of logic here is matching and extracting objects coming from Spark, and we need to test that it works for every version of Spark and Scala supported.
> 
> So unit test are useless for a big part of the code, we used them to test the internal logic of course, but that is the smaller part of the codebase.
> 
> I think we need to either include the integration test in the metric (not sure if it's possible) or drop the requirement for minimal coverage percentage.

I understand. You are missing crossbuild feature in maven.
I do not know the way how to connect two modules to measure code coverage this way. The basic idea is to measure one module only.
I see three options:
- switch project to sbt where is cross build present and applied by several projects in AbsaOSS
- drop entire jacoco GH action
- lower GH blocking percentage to acceptable value

**Comment by cerveada** [comment]
Cross-build is not a big factor here. The core issue is that we care about the test coverage (unit + integration) but we measure unit only.

**Comment by miroslavpojer** [comment]
> Cross-build is not a big factor here. The core issue is that we care about the test coverage (unit + integration) but we measure unit only.

Yes, until integration test will be outside of measured module.

**Comment by cerveada** [comment]
Spline team decision is to not use the GitHub action since unit test coverage (alone) is not a useful metric for this project, but let's keep the maven goal there for anyone if they need to check this.

**Review by cerveada — APPROVED** [review]

**Review by wajda — APPROVED** [review]

**Pull request merged**
