### PR TITLE
odpstable-fix-#820

### LINKED ISSUE #820: Spline doesn't support MaxCompute table storage?
when I try to use MaxCompute table as spark storage, the agent cannot work well.
I found that there is no relevant plugin of MaxCompute(Ali Cloud) in this repo, so it doesn't support right?
any plan for this or what?

### PR DESCRIPTION
**Pull request by BerlinJava**
fixes #820

Add a case for maxcompute table

### CODE REVIEW

**Comment by wajda** [comment]
Thank you @BerlinJava! Could you add some integration tests to this please?

**Comment by BerlinJava** [comment]
I made this change for odps table and it works well in our company where I work for, beside, as I known that Maxcompute of AliCloud related repositories are not open sources, I can not get more information from their repo， so may I know how to do that integration test ? thx

**Comment by BerlinJava** [comment]
I made this change for odps table and it works well in our company where I work for, beside, as I known that Maxcompute of AliCloud related repositories are not open sources, I can not get more information from their repo， so may I know how to do that integration test ? thx

**Review by wajda — DISMISSED** [review]
Oh, OK, if the source code is closed, and since the change is almost trivial I guess we can skip tests in this case. LGTM.

**Review by cerveada — DISMISSED** [review]
LGTM

**Comment by BerlinJava** [comment]
please help to approve again, if any query please let me know

**Pull request merged**
